name: CI - Lint & Test (Staging)

on:
  pull_request:
    branches:
      - staging

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: 🧪 Lint & Test

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: 🟨 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 📦 Install Dependencies
        run: pnpm install

      - name: 🧪 Run Tests Across Workspace
        run: pnpm -r test
